### ISSUE TITLE
How to set Cache TTL for common-caching.js?

### ISSUE THREAD

**Issue by droplinxuser** [torchbox/cloudflare-recipes#9]
I would like the cache to auto expire after **30 minutes**.
And also do I need to create a new page rule for the caching to be active?

**Comment by RealOrangeOne** [comment]
> How to set Cache TTL for common-caching.js?

This is done by Cloudflare based on the contents of the request, specifically the [`Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) header

>  And also do I need to create a new page rule for the caching to be active?

No, just for the worker to be configured for the required routes. The default caching should work fine, just make sure not to configure "Cache Everything" (as mentioned at the top of the file).
